### ISSUE TITLE
Use user's login shell to execute commands instead of executing them directly

### ISSUE THREAD

**Issue by kbrgl** [sector-f/admiral#1]
First off, I've been using Admiral for a week now and it works incredibly well. However, it's inconvenient to have to type the entire path of the binary to be run. It would be rather convenient if Admiral took inspiration from Baskerville's SXHKD and used `SHELL -c PATH` (where shell is the user's default login shell, accessible through the environment variable $SHELL and PATH is the path specified in the `admiral.toml`) to run commands. This is beneficial for three reasons:
- We no longer have to type the entire path of the binary
- Admiral now magically supports variable expansion (so that variables like `~` and `$PATH` can be automatically expanded)
- The `path` field in the `admiral.toml` can be changed from an array into a string, even when passing arguments to the program. Using arrays was inconvenient anyway.

**Comment by sector-f** [comment]
First, let me apologize for not replying sooner. I meant to, but it slipped my mind.

I can definitely see the appeal of this. It does make configuration easier (and more powerful due to being able to use environment variables).

However, shells are rather "heavy" compared to syscalls. Because of this, I'm afraid using a separate shell for each command would cause Admiral to become too resource-intensive. This is why I originally decided against using shells for this.

Have you done any comparisons between the processor and memory usage of my version and your version? (I will when I have the time, hopefully later today.) If it turns out the difference is negligible, there's a really high chance that I'll accept your pull request.

**Comment by kbrgl** [comment]
I did a naive memory / CPU usage test using `htop -p`; the difference appears to be negligible (none, actually) with the example `admiral.toml` that's been provided.

The differences become more apparent with a larger `admiral.toml` -- with my own `admiral.toml`, **my version as the same CPU usage** but consumes 3x more memory than your version.

You're clearly right, my version definitely consumes more memory. However, although the memory usage is negligible (my version consumes about 5 or 6 megabytes, even with large `admiral.toml`s), the usability of the `admiral.toml` (or lack thereof) cannot be ignored. It's pesky to have to write a new shell script every time I want to use pipes or variables (which I need to do pretty often). This has been my major complaint as a user.

At the end of the day, it's all about choosing trade-offs. As a user, I would much rather use a robust and easy-to-configure program than one that saves me a couple of megs of memory.

**Comment by sector-f** [comment]
Alright, I've put some thought into this. Here's my idea:

Use a shell for commands by default. You're right about its advantages. However, I don't think using `$SHELL` is the correct approach. I personally use zsh as my interactive shell but write my shell scripts in bash due to its portability. I doubt I'm the only one like that.

I suggest the addition of a `shell` variable to `[admiral]` that lets the user specify which shell to use for the execution of commands. If this variable is unspecified, I believe `/bin/sh` is the sanest fallback.

I additionally suggest the addition of a boolean command variable `noshell` (or something similar) to bypass the use of a shell and execute the command directly.

What do you think about that?

**Comment by kbrgl** [comment]
I think you've misunderstood the `SHELL -c` method. `SHELL -c COMMAND` executes the command the same way that running it in your terminal (which itself is a shell) would: it simply executes the file with the program specified in the shebang line -- this would be the line which says `#!/bin/bash` or `#!/bin/sh` or whatever. In the case of binaries like echo, it will execute them directly. The shell itself never touches the file, it only executes it. Thus, Bash scripts can continue being run in Bash. In fact, any program written in any language can still be run.

Also, I think that users would prefer running the programs in their default shell - as compared to `/bin/sh`, this seems like the more sane default.

The `shell` and `noshell` variables in the config file sound great. However, these should probably be kept as overrides for the default `$SHELL` behavior. This is because daemons like SXHKD (which comes with BSPWM) also use the `$SHELL` variable by default. They will expect that Admiral does the same.

What I suggest is that we implement the `$SHELL` variable as default behavior, and allow the user to specify `shell` and `noshell` as overrides.

**Comment by sector-f** [comment]
> `SHELL -c COMMAND` executes the command the same way that running it in your terminal

Ah, alright. I was misunderstanding. You're right, using `$SHELL` by default would be best then. And I suppose `shell` should be per-command rather than global.

**Comment by kbrgl** [comment]
Should I implement this feature? I'll add it to my pull request. Seems pretty easy to implement.

**Comment by sector-f** [comment]
Yes, that would be great

**Comment by kbrgl** [comment]
Alright -- this has been implemented! The PR can be merged now.

**Comment by sector-f** [comment]
Alright, just merged it.
